/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CanvasPanelMenu.java
 *
 * Created on 22.Kas.2011, 23:38:17
 */

package applet_algorithm;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JDialog;

/**
 *
 * @author bibi
 */
public class CanvasPanelMenu extends javax.swing.JPanel {

    /** Creates new form CanvasPanelMenu */
    public CanvasPanelMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorButton = new javax.swing.JButton();
        descriptionTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(500, 30));

        colorButton.setText("New Route");
        colorButton.setName("colorButton"); // NOI18N
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        descriptionTextField.setText("");
        descriptionTextField.setName("descriptionTextField"); // NOI18N
        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });

        descriptionLabel.setText("Give your map a name");
        descriptionLabel.setName("descriptionLabel"); // NOI18N


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorButton)
                .addGap(34, 34, 34)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(descriptionLabel))
            .addComponent(colorButton)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        ColorDialog c = new ColorDialog();
    }//GEN-LAST:event_colorButtonActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        CanvasApplet.canvasPanel.mapDescription = descriptionTextField.getText();
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    public String getDesc(){
        return descriptionTextField.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    // End of variables declaration//GEN-END:variables

}
class ColorDialog extends JDialog{
	private JColorChooser colorChooser = new JColorChooser ();
	private JButton okButton = new JButton ("OK");
	private JButton cancelButton = new JButton ("Cancel");
	public ColorDialog() {
			setLayout(new FlowLayout());
			setTitle("Choose a different color for a new route. Same colored edges are interpreted as the same route.");
			add(colorChooser);
			add(okButton);
			add(cancelButton);
			pack();
			setVisible(true);
			okButton.addActionListener(new ActionListener () {
				public void actionPerformed(ActionEvent a) {
					CanvasApplet.currentColor = colorChooser.getColor();
					setVisible(false);
				}
			});
	}
}