/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package applet_algorithm;

/*
 * To change this template, choose Tools | Templates
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CanvasAppletMenuBottom.java
 *
 * Created on 23.Kas.2011, 00:28:13
 */


import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author bibi
 */
public class CanvasAppletMenuBottom extends javax.swing.JPanel {

    /** Creates new form CanvasAppletMenuBottom */
    public CanvasAppletMenuBottom() {
        initComponents();
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(500, 50));

        jButton1.setText("Start Schematizing");
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent e){
        MyPoint p = new MyPoint(0,0);
        p.outgoingPoints.add(CanvasApplet.canvasPanel.returnSmallesPoint());
        try{
        Algorithm deneme= new Algorithm(p, "",1);
        p = deneme.Schematize();
        Vector<MyPoint> temp = new Vector<MyPoint>();
        CanvasApplet.canvasPanel.points=p.returnaccesiblepoints();
        CanvasApplet.canvasPanel.repaint();
        }catch(IOException f){}
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    // End of variables declaration

}

