/*
 * To change this template, choose Tools | Templates
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CanvasAppletMenuBottom.java
 *
 * Created on 23.Kas.2011, 00:28:13
 */

package applet_algorithm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author bibi
 */
public class CanvasAppletMenuBottom extends javax.swing.JPanel {

    /** Creates new form CanvasAppletMenuBottom */
    public CanvasAppletMenuBottom() {
        initComponents();
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        searchButton.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                searchButtonActionPerformed();
            }

        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(500, 50));

        jButton1.setText("Start Schematizing");
        jButton1.setName("jButton1"); // NOI18N
        searchButton.setText("Search Maps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(searchButton))
                .addContainerGap())
        );
    }// </editor-fold>

    private void jButton1ActionPerformed(ActionEvent e){
        MyPoint p = new MyPoint(0,0);
        Vector<MyPoint> temp = new Vector<MyPoint>();
        Vector<MyPoint> accs = new Vector<MyPoint>();
        //p.outgoingPoints.add(CanvasApplet.canvasPanel.returnSmallesPoint());
        try{

            if(CanvasApplet.isDefault){
                ArrayList<Connection> strpoints = CanvasApplet.canvasPanel.connections.get(0).findStartingPoints();
                for(int i=0;i<strpoints.size();i++){
                    p.outgoingPoints.add(strpoints.get(i).p1);
                    Algorithm alg = new Algorithm(p,"",1);
                    p = alg.Schematize();
                    accs = p.returnaccesiblepoints();
                    for(int j=0;j<accs.size();j++){
                        temp.add(accs.get(j));
                    }
                    p= new MyPoint(0,0);
                }
            } else{
                ArrayList<Connection> strpoints = CanvasApplet.canvasPanel.connections.get(0).findStartingPoints();
                for(int i=0;i<strpoints.size();i++){
                    p.outgoingPoints.add(strpoints.get(i).p1);
                    Algorithm deneme = new Algorithm(p,"",1,CanvasApplet.angleMultiple,CanvasApplet.ew,CanvasApplet.ns,CanvasApplet.dist);
                    p = deneme.Schematize();
                    accs = p.returnaccesiblepoints();
                    for(int j=0;j<accs.size();j++){
                        temp.add(accs.get(j));
                    }
                    p= new MyPoint(0,0);
                }
            }
        CanvasApplet.canvasPanel.points=temp;
        CanvasApplet.canvasPanel.repaint();
        }catch(IOException f){}
    }
    private void searchButtonActionPerformed(){
        //SEARCH OLAYI BURADA OLACAK!!! @EYLUL,YEKTA,OZGUR
        JOptionPane.showMessageDialog(null, "Search results.");
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton searchButton;
    // End of variables declaration

}

